version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "personal-website-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n35g8szipyd3"
s3_prefix = "personal-website-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
